#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org


EXTRA_COMMANDS="backup restore"
EXTRA_HELP=<<EOF
	backup  saves a copy of the service
    restore restores a saved a copy of the service
EOF

START=50
STOP=50


start() {
	mkdir /tmp/tftp
	kill inetd
	inetd

#setting the MAC address for eth0 and eth0.1 as for the lan 
	config_load network
	local macaddr 
	config_get macaddr lan macaddr 
	logger "macaddr = ${macaddr}"
	ifconfig eth0 down
	ifconfig eth0 hw ether "${macaddr}"
	ifconfig eth0 up
	ifconfig eth0.1 down
	ifconfig eth0.1 hw ether "${macaddr}"
	ifconfig eth0.1 up
	
	#se esiste ASACZ_previous ma non esiste ASACZ, ASACZ_previous –> ASACZ
	if [ -e "/usr/ASACZ_previous" ] 
	then
		if [ -e "/usr/ASACZ" ] 
		then
			logger "ASACZ already exists, no need to look for previous"
		else
			logger "copying ASACZ previous to ASACZ"
			cp /usr/ASACZ_previous /usr/ASACZ
		fi
	fi
	
	sleep 1
	# if ASACZ server already running, avoid to start it
	pid_mine="$$"
	pids="$(pidof ASACZ)"
	counterASACZ = 0
	for pid in $pids; do
		[ "$pid" = "$pid_mine" ] && continue
		if [ -e "/proc/$pid/stat" ] 
		then
			counterASACZ=$(( $counterASACZ + 1 ))
			logger "ASACZ server already running with pid $pid"
		fi
	done
	if [ $counterASACZ -gt 0 ]
	then
		logger "No need to start ASACZ server, was already running"
	else
		logger "Starting ASACZ server"
		/usr/ASACZ &
	fi
	
}

stop() {
	local pid
	local pids
	local pid_mine
	logger "Stopping ASACZ server"

	stop
	# kill active ASACZ servers
	pid_mine="$$"
	pids="$(pidof ASACZ)"
	for pid in $pids; do
		logger "Stopping ASACZ server with pid $pid"
		[ "$pid" = "$pid_mine" ] && continue
		[ -e "/proc/$pid/stat" ] && kill $pid
	done
	
	# wait for previous ASACZ servers stopping, with an overall timeout of 30 seconds
	counter = 0
	for pid in $pids; do
		[ "$pid" = "$pid_mine" ] && continue
		while [ -e "/proc/$pid/stat" ]
		do
			sleep 1
			counter=$(( $counter + 1 ))
			if [ $counter -gt 30 ]
			then
				logger "ERROR: timeout waiting for ASACZ server with pid $pid, cnt = $counter"
				break
			fi
			if [ $counter -gt 1 ]
			then
				logger "Waiting for ASACZ server with pid $pid, cnt = $counter"
			fi
		done
		if [ -e "/proc/$pid/stat" ]
		then
			logger "ERROR: Unable to stop ASACZ server with pid $pid"
		else
			logger "OK: ASACZ server with pid $pid stopped OK"
		fi
	done
}

restart() {
	stop "$@"
	sleep 3
	start "$@"
}

backup() {
	if [ -e "/usr/ASACZ" ] 
	then
		logger "backup ASACZ to ASACZ previous"
		cp /usr/ASACZ /usr/ASACZ_previous
	fi
}

restore() {
	if [ -e "/usr/ASACZ_previous" ] 
	then
		logger "restore ASACZ from ASACZ previous"
		cp /usr/ASACZ_previous /usr/ASACZ
	fi
}
