#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
STOP=50


start() {
	logger "Starting ASACZ server"

#setting the MAC address for eth0 and eth0.1 as for the lan 
	config_load network
	local macaddr 
	config_get macaddr lan macaddr 
	logger "macaddr = ${macaddr}"
	ifconfig eth0 down
	ifconfig eth0 hw ether "${macaddr}"
	ifconfig eth0 up
	ifconfig eth0.1 down
	ifconfig eth0.1 hw ether "${macaddr}"
	ifconfig eth0.1 up
	logger "done"

	/usr/ASACZ &
}

stop() {
	local pid
	local pids
	local pid_mine
	logger "Stopping ASACZ server"

	stop

	# kill active ASACZ servers
	pid_mine="$$"
	pids="$(pidof ASACZ)"
	for pid in $pids; do
		logger "Stopping ASACZ server with pid $pid"
		[ "$pid" = "$pid_mine" ] && continue
		[ -e "/proc/$pid/stat" ] && kill $pid
	done
}

