#!/bin/sh /etc/rc.common

START=10
STOP=15

start()
{
	logger "Setting CC265x reset as active  (GPIO_12=0)"
	# enable gpio0 12 = DCD = RESETn ATTIVO BASSO
	echo 12 > /sys/class/gpio/export
	echo "out" > /sys/class/gpio/gpio12/direction
	chmod 777 /sys/class/gpio/gpio12/value
	#force reset active
	echo 0 > /sys/class/gpio/gpio12/value

	logger "Setting CC265x boot enable as NOT ACTIVE (GPIO_0=0)"
	# enable gpio0 = CC265x boot enable pin attivo ALTO
	echo 0 > /sys/class/gpio/export
	echo "out" > /sys/class/gpio/gpio0/direction
	chmod 777 /sys/class/gpio/gpio0/value
	echo 0 > /sys/class/gpio/gpio0/value

	logger "Setting CC265x reset as NOT ACTIVE (GPIO_12=1)"
	#force reset NOT active
	echo 1 > /sys/class/gpio/gpio12/value
}

stop() {          
        echo stop
        # commands to kill application 
}


